package:
  name: thedoctor
  version: 0.3

source:
  git_url: git@github.com:hhuuggoo/thedoctor.git

requirements:
  build:
    - python

  run:
    - python
    - numpy
about:
  home: https://github.com/hhuuggoo/thedoctor
  license: BSD
