package:
  name: thedoctor
  version: 0.3

source:
  git_url: git@github.com:hhuuggoo/thedoctor.git

requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  requires:
    - nose
    - flake8
    - flake8-import-order
    - coverage
    - pandas

  commands:
    - nosetests --with-doctest --with-coverage --cover-package=thedoctor
    - flake8 thedoctor

about:
  home: https://github.com/hhuuggoo/thedoctor
  license: BSD
