package:
  name: thedoctor
  version: 0.2

source:
  git_url: git@github.com:hhuuggoo/thedoctor.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{environ.get('PY_VER').replace('.', '')}}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}

requirements:
  build:
    - python

  run:
    - python

about:
  home: https://github.com/ContinuumIO/thedoctor
  license: BSD
